// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	pgvector "github.com/pgvector/pgvector-go"
)

const approveJobApproval = `-- name: ApproveJobApproval :execrows
UPDATE job_approval_requests
SET status = 'approved', reviewed_by = $3, reviewed_at = $4
WHERE job_id = $1 AND approval_id = $2
`

type ApproveJobApprovalParams struct {
	JobID      string
	ApprovalID string
	ReviewedBy string
	ReviewedAt sql.NullTime
}

func (q *Queries) ApproveJobApproval(ctx context.Context, arg ApproveJobApprovalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, approveJobApproval,
		arg.JobID,
		arg.ApprovalID,
		arg.ReviewedBy,
		arg.ReviewedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeProcessingJob = `-- name: CompleteProcessingJob :execrows
UPDATE document_processing_jobs
SET status = 'succeeded',
    current_stage = '',
    plan_status = 'completed',
    evaluation_status = 'passed',
    updated_at = $2
WHERE job_id = $1
`

type CompleteProcessingJobParams struct {
	JobID     string
	UpdatedAt time.Time
}

func (q *Queries) CompleteProcessingJob(ctx context.Context, arg CompleteProcessingJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeProcessingJob, arg.JobID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countApprovedAliases = `-- name: CountApprovedAliases :one
SELECT COUNT(*)
FROM item_aliases
INNER JOIN tree_items canonical_items ON canonical_items.id = item_aliases.canonical_item_id
INNER JOIN tree_items alias_items ON alias_items.id = item_aliases.alias_item_id
WHERE item_aliases.workspace_id = $1
  AND item_aliases.status = 'approved'
  AND canonical_items.workspace_id = $2
  AND alias_items.workspace_id = $2
`

type CountApprovedAliasesParams struct {
	WorkspaceID   string
	WorkspaceID_2 string
}

func (q *Queries) CountApprovedAliases(ctx context.Context, arg CountApprovedAliasesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApprovedAliases, arg.WorkspaceID, arg.WorkspaceID_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobMutationLogs = `-- name: CountJobMutationLogs :one
SELECT COUNT(*)
FROM job_mutation_logs
WHERE job_id = $1
`

func (q *Queries) CountJobMutationLogs(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobMutationLogs, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProtectedAliases = `-- name: CountProtectedAliases :one
SELECT COUNT(*)
FROM item_aliases
INNER JOIN tree_items canonical_items ON canonical_items.id = item_aliases.canonical_item_id
INNER JOIN tree_items alias_items ON alias_items.id = item_aliases.alias_item_id
WHERE item_aliases.workspace_id = $1
  AND item_aliases.status = 'approved'
  AND canonical_items.workspace_id = $2
  AND alias_items.workspace_id = $2
  AND (
    canonical_items.governance_state IN ('human_curated', 'locked')
    OR alias_items.governance_state IN ('human_curated', 'locked')
  )
`

type CountProtectedAliasesParams struct {
	WorkspaceID   string
	WorkspaceID_2 string
}

func (q *Queries) CountProtectedAliases(ctx context.Context, arg CountProtectedAliasesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProtectedAliases, arg.WorkspaceID, arg.WorkspaceID_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSameDocumentItems = `-- name: CountSameDocumentItems :one
SELECT COUNT(DISTINCT item_sources.item_id)
FROM item_sources
INNER JOIN tree_items ON tree_items.id = item_sources.item_id
WHERE item_sources.document_id = $1
  AND tree_items.workspace_id = $2
`

type CountSameDocumentItemsParams struct {
	DocumentID  string
	WorkspaceID string
}

func (q *Queries) CountSameDocumentItems(ctx context.Context, arg CountSameDocumentItemsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSameDocumentItems, arg.DocumentID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents (document_id, workspace_id, uploaded_by, filename, mime_type, file_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateDocumentParams struct {
	DocumentID  string
	WorkspaceID string
	UploadedBy  string
	Filename    string
	MimeType    string
	FileSize    int64
	CreatedAt   time.Time
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, createDocument,
		arg.DocumentID,
		arg.WorkspaceID,
		arg.UploadedBy,
		arg.Filename,
		arg.MimeType,
		arg.FileSize,
		arg.CreatedAt,
	)
	return err
}

const createDocumentChunk = `-- name: CreateDocumentChunk :exec
INSERT INTO document_chunks (chunk_id, document_id, heading, text, source_page, embedding)
VALUES ($1, $2, $3, $4, $5, $6::vector)
`

type CreateDocumentChunkParams struct {
	ChunkID    string
	DocumentID string
	Heading    string
	Text       string
	SourcePage sql.NullInt32
	Embedding  pgvector.Vector
}

func (q *Queries) CreateDocumentChunk(ctx context.Context, arg CreateDocumentChunkParams) error {
	_, err := q.db.ExecContext(ctx, createDocumentChunk,
		arg.ChunkID,
		arg.DocumentID,
		arg.Heading,
		arg.Text,
		arg.SourcePage,
		arg.Embedding,
	)
	return err
}

const createJobApprovalRequest = `-- name: CreateJobApprovalRequest :exec
INSERT INTO job_approval_requests (
  approval_id, job_id, plan_id, status, requested_operations_json, reason, risk_tier,
  requested_by, reviewed_by, requested_at, reviewed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateJobApprovalRequestParams struct {
	ApprovalID              string
	JobID                   string
	PlanID                  string
	Status                  string
	RequestedOperationsJson string
	Reason                  string
	RiskTier                string
	RequestedBy             string
	ReviewedBy              string
	RequestedAt             time.Time
	ReviewedAt              sql.NullTime
}

func (q *Queries) CreateJobApprovalRequest(ctx context.Context, arg CreateJobApprovalRequestParams) error {
	_, err := q.db.ExecContext(ctx, createJobApprovalRequest,
		arg.ApprovalID,
		arg.JobID,
		arg.PlanID,
		arg.Status,
		arg.RequestedOperationsJson,
		arg.Reason,
		arg.RiskTier,
		arg.RequestedBy,
		arg.ReviewedBy,
		arg.RequestedAt,
		arg.ReviewedAt,
	)
	return err
}

const createJobCapability = `-- name: CreateJobCapability :exec
INSERT INTO job_capabilities (
  capability_id, job_id, workspace_id, allowed_document_ids_json, allowed_item_ids_json,
  allowed_operations_json, max_llm_calls, max_tool_runs, max_item_creations, expires_at, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateJobCapabilityParams struct {
	CapabilityID           string
	JobID                  string
	WorkspaceID            string
	AllowedDocumentIdsJson string
	AllowedItemIdsJson     string
	AllowedOperationsJson  string
	MaxLlmCalls            int32
	MaxToolRuns            int32
	MaxItemCreations       int32
	ExpiresAt              time.Time
	CreatedAt              time.Time
}

func (q *Queries) CreateJobCapability(ctx context.Context, arg CreateJobCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, createJobCapability,
		arg.CapabilityID,
		arg.JobID,
		arg.WorkspaceID,
		arg.AllowedDocumentIdsJson,
		arg.AllowedItemIdsJson,
		arg.AllowedOperationsJson,
		arg.MaxLlmCalls,
		arg.MaxToolRuns,
		arg.MaxItemCreations,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createJobMutationLog = `-- name: CreateJobMutationLog :exec
INSERT INTO job_mutation_logs (
  mutation_id, job_id, workspace_id, target_type, target_id, mutation_type, 
  risk_tier, before_json, after_json, provenance_json, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateJobMutationLogParams struct {
	MutationID     string
	JobID          string
	WorkspaceID    string
	TargetType     string
	TargetID       string
	MutationType   string
	RiskTier       string
	BeforeJson     string
	AfterJson      string
	ProvenanceJson string
	CreatedAt      time.Time
}

func (q *Queries) CreateJobMutationLog(ctx context.Context, arg CreateJobMutationLogParams) error {
	_, err := q.db.ExecContext(ctx, createJobMutationLog,
		arg.MutationID,
		arg.JobID,
		arg.WorkspaceID,
		arg.TargetType,
		arg.TargetID,
		arg.MutationType,
		arg.RiskTier,
		arg.BeforeJson,
		arg.AfterJson,
		arg.ProvenanceJson,
		arg.CreatedAt,
	)
	return err
}

const createProcessingJob = `-- name: CreateProcessingJob :exec
INSERT INTO document_processing_jobs (
  job_id, document_id, workspace_id, job_type, status, current_stage, error_message, params_json,
  requested_by, capability_id, execution_plan_id, plan_status, evaluation_status, retry_count, budget_json,
  created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $16)
`

type CreateProcessingJobParams struct {
	JobID            string
	DocumentID       string
	WorkspaceID      string
	JobType          string
	Status           string
	CurrentStage     string
	ErrorMessage     string
	ParamsJson       string
	RequestedBy      string
	CapabilityID     string
	ExecutionPlanID  string
	PlanStatus       string
	EvaluationStatus string
	RetryCount       int32
	BudgetJson       string
	CreatedAt        time.Time
}

func (q *Queries) CreateProcessingJob(ctx context.Context, arg CreateProcessingJobParams) error {
	_, err := q.db.ExecContext(ctx, createProcessingJob,
		arg.JobID,
		arg.DocumentID,
		arg.WorkspaceID,
		arg.JobType,
		arg.Status,
		arg.CurrentStage,
		arg.ErrorMessage,
		arg.ParamsJson,
		arg.RequestedBy,
		arg.CapabilityID,
		arg.ExecutionPlanID,
		arg.PlanStatus,
		arg.EvaluationStatus,
		arg.RetryCount,
		arg.BudgetJson,
		arg.CreatedAt,
	)
	return err
}

const deleteDocumentChunks = `-- name: DeleteDocumentChunks :exec
DELETE FROM document_chunks
WHERE document_id = $1
`

func (q *Queries) DeleteDocumentChunks(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentChunks, documentID)
	return err
}

const failProcessingJob = `-- name: FailProcessingJob :execrows
UPDATE document_processing_jobs
SET status = 'failed',
    error_message = $2,
    evaluation_status = 'failed',
    updated_at = $3
WHERE job_id = $1
`

type FailProcessingJobParams struct {
	JobID        string
	ErrorMessage string
	UpdatedAt    time.Time
}

func (q *Queries) FailProcessingJob(ctx context.Context, arg FailProcessingJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failProcessingJob, arg.JobID, arg.ErrorMessage, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocument = `-- name: GetDocument :one
SELECT document_id, workspace_id, uploaded_by, filename, mime_type, file_size, created_at
FROM documents
WHERE document_id = $1
`

func (q *Queries) GetDocument(ctx context.Context, documentID string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, documentID)
	var i Document
	err := row.Scan(
		&i.DocumentID,
		&i.WorkspaceID,
		&i.UploadedBy,
		&i.Filename,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const getJobApprovalPlanID = `-- name: GetJobApprovalPlanID :one
SELECT plan_id
FROM job_approval_requests
WHERE job_id = $1 AND approval_id = $2
`

type GetJobApprovalPlanIDParams struct {
	JobID      string
	ApprovalID string
}

func (q *Queries) GetJobApprovalPlanID(ctx context.Context, arg GetJobApprovalPlanIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getJobApprovalPlanID, arg.JobID, arg.ApprovalID)
	var plan_id string
	err := row.Scan(&plan_id)
	return plan_id, err
}

const getJobCapability = `-- name: GetJobCapability :one
SELECT capability_id, job_id, workspace_id, allowed_document_ids_json, allowed_item_ids_json,
       allowed_operations_json, max_llm_calls, max_tool_runs, max_item_creations, expires_at, created_at
FROM job_capabilities
WHERE job_id = $1
`

func (q *Queries) GetJobCapability(ctx context.Context, jobID string) (JobCapability, error) {
	row := q.db.QueryRowContext(ctx, getJobCapability, jobID)
	var i JobCapability
	err := row.Scan(
		&i.CapabilityID,
		&i.JobID,
		&i.WorkspaceID,
		&i.AllowedDocumentIdsJson,
		&i.AllowedItemIdsJson,
		&i.AllowedOperationsJson,
		&i.MaxLlmCalls,
		&i.MaxToolRuns,
		&i.MaxItemCreations,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJobExecutionPlan = `-- name: GetJobExecutionPlan :one
SELECT plan_id, job_id, status, summary, plan_json, created_by, created_at, updated_at
FROM job_execution_plans
WHERE job_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetJobExecutionPlan(ctx context.Context, jobID string) (JobExecutionPlan, error) {
	row := q.db.QueryRowContext(ctx, getJobExecutionPlan, jobID)
	var i JobExecutionPlan
	err := row.Scan(
		&i.PlanID,
		&i.JobID,
		&i.Status,
		&i.Summary,
		&i.PlanJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestProcessingJob = `-- name: GetLatestProcessingJob :one
SELECT job_id, document_id, workspace_id, job_type, status, current_stage, error_message, params_json,
       requested_by, capability_id, execution_plan_id, plan_status, evaluation_status, retry_count, budget_json,
       created_at, updated_at
FROM document_processing_jobs
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestProcessingJob(ctx context.Context, documentID string) (DocumentProcessingJob, error) {
	row := q.db.QueryRowContext(ctx, getLatestProcessingJob, documentID)
	var i DocumentProcessingJob
	err := row.Scan(
		&i.JobID,
		&i.DocumentID,
		&i.WorkspaceID,
		&i.JobType,
		&i.Status,
		&i.CurrentStage,
		&i.ErrorMessage,
		&i.ParamsJson,
		&i.RequestedBy,
		&i.CapabilityID,
		&i.ExecutionPlanID,
		&i.PlanStatus,
		&i.EvaluationStatus,
		&i.RetryCount,
		&i.BudgetJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProcessingJob = `-- name: GetProcessingJob :one
SELECT job_id, document_id, workspace_id, job_type, status, current_stage, error_message, params_json,
       requested_by, capability_id, execution_plan_id, plan_status, evaluation_status, retry_count, budget_json,
       created_at, updated_at
FROM document_processing_jobs
WHERE job_id = $1
`

func (q *Queries) GetProcessingJob(ctx context.Context, jobID string) (DocumentProcessingJob, error) {
	row := q.db.QueryRowContext(ctx, getProcessingJob, jobID)
	var i DocumentProcessingJob
	err := row.Scan(
		&i.JobID,
		&i.DocumentID,
		&i.WorkspaceID,
		&i.JobType,
		&i.Status,
		&i.CurrentStage,
		&i.ErrorMessage,
		&i.ParamsJson,
		&i.RequestedBy,
		&i.CapabilityID,
		&i.ExecutionPlanID,
		&i.PlanStatus,
		&i.EvaluationStatus,
		&i.RetryCount,
		&i.BudgetJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllJobs = `-- name: ListAllJobs :many
SELECT job_id, document_id, workspace_id, job_type, status, current_stage, error_message, params_json,
       requested_by, capability_id, execution_plan_id, plan_status, evaluation_status, retry_count, budget_json,
       created_at, updated_at
FROM document_processing_jobs
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListAllJobs(ctx context.Context) ([]DocumentProcessingJob, error) {
	rows, err := q.db.QueryContext(ctx, listAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentProcessingJob
	for rows.Next() {
		var i DocumentProcessingJob
		if err := rows.Scan(
			&i.JobID,
			&i.DocumentID,
			&i.WorkspaceID,
			&i.JobType,
			&i.Status,
			&i.CurrentStage,
			&i.ErrorMessage,
			&i.ParamsJson,
			&i.RequestedBy,
			&i.CapabilityID,
			&i.ExecutionPlanID,
			&i.PlanStatus,
			&i.EvaluationStatus,
			&i.RetryCount,
			&i.BudgetJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentChunks = `-- name: ListDocumentChunks :many
SELECT chunk_id, document_id, heading, text, source_page
FROM document_chunks
WHERE document_id = $1
ORDER BY chunk_id
`

type ListDocumentChunksRow struct {
	ChunkID    string
	DocumentID string
	Heading    string
	Text       string
	SourcePage sql.NullInt32
}

func (q *Queries) ListDocumentChunks(ctx context.Context, documentID string) ([]ListDocumentChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentChunks, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentChunksRow
	for rows.Next() {
		var i ListDocumentChunksRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.DocumentID,
			&i.Heading,
			&i.Text,
			&i.SourcePage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT document_id, workspace_id, uploaded_by, filename, mime_type, file_size, created_at
FROM documents
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context, workspaceID string) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.DocumentID,
			&i.WorkspaceID,
			&i.UploadedBy,
			&i.Filename,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobApprovalRequests = `-- name: ListJobApprovalRequests :many
SELECT approval_id, job_id, plan_id, status, requested_operations_json, reason, risk_tier,
       requested_by, reviewed_by, requested_at, reviewed_at
FROM job_approval_requests
WHERE job_id = $1
ORDER BY requested_at DESC
`

func (q *Queries) ListJobApprovalRequests(ctx context.Context, jobID string) ([]JobApprovalRequest, error) {
	rows, err := q.db.QueryContext(ctx, listJobApprovalRequests, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApprovalRequest
	for rows.Next() {
		var i JobApprovalRequest
		if err := rows.Scan(
			&i.ApprovalID,
			&i.JobID,
			&i.PlanID,
			&i.Status,
			&i.RequestedOperationsJson,
			&i.Reason,
			&i.RiskTier,
			&i.RequestedBy,
			&i.ReviewedBy,
			&i.RequestedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobMutationLogs = `-- name: ListJobMutationLogs :many
SELECT mutation_id, job_id, plan_id, capability_id, workspace_id, target_type, target_id, mutation_type, 
       risk_tier, before_json, after_json, provenance_json, created_at
FROM job_mutation_logs
WHERE job_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListJobMutationLogs(ctx context.Context, jobID string) ([]JobMutationLog, error) {
	rows, err := q.db.QueryContext(ctx, listJobMutationLogs, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobMutationLog
	for rows.Next() {
		var i JobMutationLog
		if err := rows.Scan(
			&i.MutationID,
			&i.JobID,
			&i.PlanID,
			&i.CapabilityID,
			&i.WorkspaceID,
			&i.TargetType,
			&i.TargetID,
			&i.MutationType,
			&i.RiskTier,
			&i.BeforeJson,
			&i.AfterJson,
			&i.ProvenanceJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProcessingJobRunning = `-- name: MarkProcessingJobRunning :execrows
UPDATE document_processing_jobs
SET status = 'running',
    error_message = '',
    plan_status = CASE WHEN plan_status IN ('', 'approved', 'none') THEN 'executing' ELSE plan_status END,
    updated_at = $2
WHERE job_id = $1
`

type MarkProcessingJobRunningParams struct {
	JobID     string
	UpdatedAt time.Time
}

func (q *Queries) MarkProcessingJobRunning(ctx context.Context, arg MarkProcessingJobRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markProcessingJobRunning, arg.JobID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rejectJobApproval = `-- name: RejectJobApproval :execrows
UPDATE job_approval_requests
SET status = 'rejected',
    reviewed_by = $3,
    reviewed_at = $4,
    reason = CASE WHEN $5 = '' THEN reason ELSE $5 END
WHERE job_id = $1 AND approval_id = $2
`

type RejectJobApprovalParams struct {
	JobID      string
	ApprovalID string
	ReviewedBy string
	ReviewedAt sql.NullTime
	Column5    interface{}
}

func (q *Queries) RejectJobApproval(ctx context.Context, arg RejectJobApprovalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rejectJobApproval,
		arg.JobID,
		arg.ApprovalID,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchWorkspaceDocumentChunksByText = `-- name: SearchWorkspaceDocumentChunksByText :many
SELECT c.chunk_id, c.document_id, c.heading, c.text, c.source_page
FROM document_chunks c
INNER JOIN documents d ON d.document_id = c.document_id
WHERE d.workspace_id = $1
  AND ($2::text = '%' OR LOWER(c.heading || ' ' || c.text) LIKE $2::text)
ORDER BY c.chunk_id
LIMIT $3
`

type SearchWorkspaceDocumentChunksByTextParams struct {
	WorkspaceID string
	Pattern     string
	ResultLimit int32
}

type SearchWorkspaceDocumentChunksByTextRow struct {
	ChunkID    string
	DocumentID string
	Heading    string
	Text       string
	SourcePage sql.NullInt32
}

func (q *Queries) SearchWorkspaceDocumentChunksByText(ctx context.Context, arg SearchWorkspaceDocumentChunksByTextParams) ([]SearchWorkspaceDocumentChunksByTextRow, error) {
	rows, err := q.db.QueryContext(ctx, searchWorkspaceDocumentChunksByText, arg.WorkspaceID, arg.Pattern, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchWorkspaceDocumentChunksByTextRow
	for rows.Next() {
		var i SearchWorkspaceDocumentChunksByTextRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.DocumentID,
			&i.Heading,
			&i.Text,
			&i.SourcePage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWorkspaceDocumentChunksByVector = `-- name: SearchWorkspaceDocumentChunksByVector :many
SELECT c.chunk_id, c.document_id, c.heading, c.text, c.source_page,
       1 - (c.embedding <=> $1::vector) AS similarity
FROM document_chunks c
INNER JOIN documents d ON d.document_id = c.document_id
WHERE d.workspace_id = $2
  AND c.embedding IS NOT NULL
  AND 1 - (c.embedding <=> $1::vector) >= $3::float8
ORDER BY c.embedding <=> $1::vector
LIMIT $4
`

type SearchWorkspaceDocumentChunksByVectorParams struct {
	QueryEmbedding pgvector.Vector
	WorkspaceID    string
	MinSimilarity  float64
	ResultLimit    int32
}

type SearchWorkspaceDocumentChunksByVectorRow struct {
	ChunkID    string
	DocumentID string
	Heading    string
	Text       string
	SourcePage sql.NullInt32
	Similarity float64
}

func (q *Queries) SearchWorkspaceDocumentChunksByVector(ctx context.Context, arg SearchWorkspaceDocumentChunksByVectorParams) ([]SearchWorkspaceDocumentChunksByVectorRow, error) {
	rows, err := q.db.QueryContext(ctx, searchWorkspaceDocumentChunksByVector,
		arg.QueryEmbedding,
		arg.WorkspaceID,
		arg.MinSimilarity,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchWorkspaceDocumentChunksByVectorRow
	for rows.Next() {
		var i SearchWorkspaceDocumentChunksByVectorRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.DocumentID,
			&i.Heading,
			&i.Text,
			&i.SourcePage,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobExecutionPlanStatus = `-- name: UpdateJobExecutionPlanStatus :execrows
UPDATE job_execution_plans
SET status = $2, updated_at = $3
WHERE plan_id = $1
`

type UpdateJobExecutionPlanStatusParams struct {
	PlanID    string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateJobExecutionPlanStatus(ctx context.Context, arg UpdateJobExecutionPlanStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJobExecutionPlanStatus, arg.PlanID, arg.Status, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProcessingJobEvaluationState = `-- name: UpdateProcessingJobEvaluationState :exec
UPDATE document_processing_jobs
SET evaluation_status = $2,
    updated_at = $3
WHERE job_id = $1
`

type UpdateProcessingJobEvaluationStateParams struct {
	JobID            string
	EvaluationStatus string
	UpdatedAt        time.Time
}

func (q *Queries) UpdateProcessingJobEvaluationState(ctx context.Context, arg UpdateProcessingJobEvaluationStateParams) error {
	_, err := q.db.ExecContext(ctx, updateProcessingJobEvaluationState, arg.JobID, arg.EvaluationStatus, arg.UpdatedAt)
	return err
}

const updateProcessingJobPlanState = `-- name: UpdateProcessingJobPlanState :exec
UPDATE document_processing_jobs
SET execution_plan_id = $2,
    plan_status = $3,
    updated_at = $4
WHERE job_id = $1
`

type UpdateProcessingJobPlanStateParams struct {
	JobID           string
	ExecutionPlanID string
	PlanStatus      string
	UpdatedAt       time.Time
}

func (q *Queries) UpdateProcessingJobPlanState(ctx context.Context, arg UpdateProcessingJobPlanStateParams) error {
	_, err := q.db.ExecContext(ctx, updateProcessingJobPlanState,
		arg.JobID,
		arg.ExecutionPlanID,
		arg.PlanStatus,
		arg.UpdatedAt,
	)
	return err
}

const updateProcessingJobStage = `-- name: UpdateProcessingJobStage :exec
UPDATE document_processing_jobs
SET current_stage = $2, updated_at = $3
WHERE job_id = $1
`

type UpdateProcessingJobStageParams struct {
	JobID        string
	CurrentStage string
	UpdatedAt    time.Time
}

func (q *Queries) UpdateProcessingJobStage(ctx context.Context, arg UpdateProcessingJobStageParams) error {
	_, err := q.db.ExecContext(ctx, updateProcessingJobStage, arg.JobID, arg.CurrentStage, arg.UpdatedAt)
	return err
}

const upsertJobExecutionPlan = `-- name: UpsertJobExecutionPlan :exec
INSERT INTO job_execution_plans (plan_id, job_id, status, summary, plan_json, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (plan_id) DO UPDATE
SET status = EXCLUDED.status,
    summary = EXCLUDED.summary,
    plan_json = EXCLUDED.plan_json,
    created_by = EXCLUDED.created_by,
    updated_at = EXCLUDED.updated_at
`

type UpsertJobExecutionPlanParams struct {
	PlanID    string
	JobID     string
	Status    string
	Summary   string
	PlanJson  string
	CreatedBy string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertJobExecutionPlan(ctx context.Context, arg UpsertJobExecutionPlanParams) error {
	_, err := q.db.ExecContext(ctx, upsertJobExecutionPlan,
		arg.PlanID,
		arg.JobID,
		arg.Status,
		arg.Summary,
		arg.PlanJson,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
