// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package sqlcgen

import (
	"context"
	"time"
)

const completeProcessingJob = `-- name: CompleteProcessingJob :execrows
UPDATE document_processing_jobs
SET status = 'completed', current_stage = '', updated_at = $2
WHERE job_id = $1
`

type CompleteProcessingJobParams struct {
	JobID     string
	UpdatedAt time.Time
}

func (q *Queries) CompleteProcessingJob(ctx context.Context, arg CompleteProcessingJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeProcessingJob, arg.JobID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents (document_id, workspace_id, uploaded_by, filename, mime_type, file_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateDocumentParams struct {
	DocumentID  string
	WorkspaceID string
	UploadedBy  string
	Filename    string
	MimeType    string
	FileSize    int64
	CreatedAt   time.Time
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, createDocument,
		arg.DocumentID,
		arg.WorkspaceID,
		arg.UploadedBy,
		arg.Filename,
		arg.MimeType,
		arg.FileSize,
		arg.CreatedAt,
	)
	return err
}

const createProcessingJob = `-- name: CreateProcessingJob :exec
INSERT INTO document_processing_jobs (job_id, document_id, graph_id, job_type, status, current_stage, error_message, params_json, created_at, updated_at)
VALUES ($1, $2, NULLIF($3, ''), $4, $5, '', '', '{}', $6, $6)
`

type CreateProcessingJobParams struct {
	JobID      string
	DocumentID string
	Column3    interface{}
	JobType    string
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) CreateProcessingJob(ctx context.Context, arg CreateProcessingJobParams) error {
	_, err := q.db.ExecContext(ctx, createProcessingJob,
		arg.JobID,
		arg.DocumentID,
		arg.Column3,
		arg.JobType,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const failProcessingJob = `-- name: FailProcessingJob :execrows
UPDATE document_processing_jobs
SET status = 'failed', error_message = $2, updated_at = $3
WHERE job_id = $1
`

type FailProcessingJobParams struct {
	JobID        string
	ErrorMessage string
	UpdatedAt    time.Time
}

func (q *Queries) FailProcessingJob(ctx context.Context, arg FailProcessingJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failProcessingJob, arg.JobID, arg.ErrorMessage, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocument = `-- name: GetDocument :one
SELECT document_id, workspace_id, uploaded_by, filename, mime_type, file_size, created_at
FROM documents
WHERE document_id = $1
`

func (q *Queries) GetDocument(ctx context.Context, documentID string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, documentID)
	var i Document
	err := row.Scan(
		&i.DocumentID,
		&i.WorkspaceID,
		&i.UploadedBy,
		&i.Filename,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestProcessingJob = `-- name: GetLatestProcessingJob :one
SELECT job_id, document_id, COALESCE(graph_id, '') AS graph_id, job_type, status, current_stage, error_message, params_json, created_at, updated_at
FROM document_processing_jobs
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestProcessingJobRow struct {
	JobID        string
	DocumentID   string
	GraphID      string
	JobType      string
	Status       string
	CurrentStage string
	ErrorMessage string
	ParamsJson   string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetLatestProcessingJob(ctx context.Context, documentID string) (GetLatestProcessingJobRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestProcessingJob, documentID)
	var i GetLatestProcessingJobRow
	err := row.Scan(
		&i.JobID,
		&i.DocumentID,
		&i.GraphID,
		&i.JobType,
		&i.Status,
		&i.CurrentStage,
		&i.ErrorMessage,
		&i.ParamsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT document_id, workspace_id, uploaded_by, filename, mime_type, file_size, created_at
FROM documents
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context, workspaceID string) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.DocumentID,
			&i.WorkspaceID,
			&i.UploadedBy,
			&i.Filename,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcessingJobStage = `-- name: UpdateProcessingJobStage :exec
UPDATE document_processing_jobs
SET current_stage = $2, updated_at = $3
WHERE job_id = $1
`

type UpdateProcessingJobStageParams struct {
	JobID        string
	CurrentStage string
	UpdatedAt    time.Time
}

func (q *Queries) UpdateProcessingJobStage(ctx context.Context, arg UpdateProcessingJobStageParams) error {
	_, err := q.db.ExecContext(ctx, updateProcessingJobStage, arg.JobID, arg.CurrentStage, arg.UpdatedAt)
	return err
}
