// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createEdge = `-- name: CreateEdge :exec
INSERT INTO edges (edge_id, graph_id, source_node_id, target_node_id, edge_type, description, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateEdgeParams struct {
	EdgeID       string
	GraphID      string
	SourceNodeID string
	TargetNodeID string
	EdgeType     string
	Description  string
	CreatedAt    time.Time
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) error {
	_, err := q.db.ExecContext(ctx, createEdge,
		arg.EdgeID,
		arg.GraphID,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.EdgeType,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (node_id, graph_id, label, category, level, entity_type, description, summary_html, created_by, created_at)
VALUES ($1, $2, $3, '', $4, $5, $6, $7, $8, $9)
`

type CreateNodeParams struct {
	NodeID      string
	GraphID     string
	Label       string
	Level       int32
	EntityType  string
	Description string
	SummaryHtml string
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode,
		arg.NodeID,
		arg.GraphID,
		arg.Label,
		arg.Level,
		arg.EntityType,
		arg.Description,
		arg.SummaryHtml,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const getGraphByWorkspace = `-- name: GetGraphByWorkspace :one
SELECT graph_id, workspace_id, name, created_at, updated_at
FROM graphs
WHERE workspace_id = $1
`

func (q *Queries) GetGraphByWorkspace(ctx context.Context, workspaceID string) (Graph, error) {
	row := q.db.QueryRowContext(ctx, getGraphByWorkspace, workspaceID)
	var i Graph
	err := row.Scan(
		&i.GraphID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT node_id, graph_id, label, category, level, entity_type, description, summary_html, created_by, created_at
FROM nodes
WHERE node_id = $1
`

type GetNodeRow struct {
	NodeID      string
	GraphID     string
	Label       string
	Category    string
	Level       int32
	EntityType  string
	Description string
	SummaryHtml string
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) GetNode(ctx context.Context, nodeID string) (GetNodeRow, error) {
	row := q.db.QueryRowContext(ctx, getNode, nodeID)
	var i GetNodeRow
	err := row.Scan(
		&i.NodeID,
		&i.GraphID,
		&i.Label,
		&i.Category,
		&i.Level,
		&i.EntityType,
		&i.Description,
		&i.SummaryHtml,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateGraph = `-- name: GetOrCreateGraph :one
INSERT INTO graphs (graph_id, workspace_id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (workspace_id) DO UPDATE SET updated_at = EXCLUDED.updated_at
RETURNING graph_id, workspace_id, name, created_at, updated_at
`

type GetOrCreateGraphParams struct {
	GraphID     string
	WorkspaceID string
	Name        string
	CreatedAt   time.Time
}

func (q *Queries) GetOrCreateGraph(ctx context.Context, arg GetOrCreateGraphParams) (Graph, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateGraph,
		arg.GraphID,
		arg.WorkspaceID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Graph
	err := row.Scan(
		&i.GraphID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEdgesByGraph = `-- name: ListEdgesByGraph :many
SELECT edge_id, graph_id, source_node_id, target_node_id, edge_type, description, created_at
FROM edges
WHERE graph_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEdgesByGraph(ctx context.Context, graphID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesByGraph, graphID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.EdgeID,
			&i.GraphID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.EdgeType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeEdges = `-- name: ListNodeEdges :many
SELECT edge_id, graph_id, source_node_id, target_node_id, edge_type, description, created_at
FROM edges
WHERE source_node_id = $1 OR target_node_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListNodeEdges(ctx context.Context, sourceNodeID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, listNodeEdges, sourceNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.EdgeID,
			&i.GraphID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.EdgeType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeSources = `-- name: ListNodeSources :many
SELECT node_id, document_id, chunk_id, source_text, COALESCE(confidence, 0) AS confidence
FROM node_sources
WHERE node_id = $1
`

type ListNodeSourcesRow struct {
	NodeID     string
	DocumentID string
	ChunkID    string
	SourceText string
	Confidence float64
}

func (q *Queries) ListNodeSources(ctx context.Context, nodeID string) ([]ListNodeSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeSources, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeSourcesRow
	for rows.Next() {
		var i ListNodeSourcesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.DocumentID,
			&i.ChunkID,
			&i.SourceText,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByGraph = `-- name: ListNodesByGraph :many
SELECT node_id, graph_id, label, category, level, entity_type, description, summary_html, created_by, created_at
FROM nodes
WHERE graph_id = $1
ORDER BY created_at ASC
`

type ListNodesByGraphRow struct {
	NodeID      string
	GraphID     string
	Label       string
	Category    string
	Level       int32
	EntityType  string
	Description string
	SummaryHtml string
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) ListNodesByGraph(ctx context.Context, graphID string) ([]ListNodesByGraphRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByGraph, graphID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesByGraphRow
	for rows.Next() {
		var i ListNodesByGraphRow
		if err := rows.Scan(
			&i.NodeID,
			&i.GraphID,
			&i.Label,
			&i.Category,
			&i.Level,
			&i.EntityType,
			&i.Description,
			&i.SummaryHtml,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGraphTimestamp = `-- name: UpdateGraphTimestamp :exec
UPDATE graphs
SET updated_at = $2
WHERE graph_id = $1
`

type UpdateGraphTimestampParams struct {
	GraphID   string
	UpdatedAt time.Time
}

func (q *Queries) UpdateGraphTimestamp(ctx context.Context, arg UpdateGraphTimestampParams) error {
	_, err := q.db.ExecContext(ctx, updateGraphTimestamp, arg.GraphID, arg.UpdatedAt)
	return err
}

const upsertApprovedAlias = `-- name: UpsertApprovedAlias :exec
INSERT INTO node_aliases (workspace_id, canonical_node_id, alias_node_id, status, updated_at)
VALUES ($1, $2, $3, 'approved', $4)
ON CONFLICT (workspace_id, canonical_node_id, alias_node_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = EXCLUDED.updated_at
`

type UpsertApprovedAliasParams struct {
	WorkspaceID     string
	CanonicalNodeID string
	AliasNodeID     string
	UpdatedAt       time.Time
}

func (q *Queries) UpsertApprovedAlias(ctx context.Context, arg UpsertApprovedAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertApprovedAlias,
		arg.WorkspaceID,
		arg.CanonicalNodeID,
		arg.AliasNodeID,
		arg.UpdatedAt,
	)
	return err
}

const upsertEdgeSource = `-- name: UpsertEdgeSource :exec
INSERT INTO edge_sources (edge_id, document_id, chunk_id, source_text, confidence)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (edge_id, document_id, chunk_id)
DO UPDATE SET source_text = EXCLUDED.source_text, confidence = EXCLUDED.confidence
`

type UpsertEdgeSourceParams struct {
	EdgeID     string
	DocumentID string
	ChunkID    string
	SourceText string
	Confidence sql.NullFloat64
}

func (q *Queries) UpsertEdgeSource(ctx context.Context, arg UpsertEdgeSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertEdgeSource,
		arg.EdgeID,
		arg.DocumentID,
		arg.ChunkID,
		arg.SourceText,
		arg.Confidence,
	)
	return err
}

const upsertNodeSource = `-- name: UpsertNodeSource :exec
INSERT INTO node_sources (node_id, document_id, chunk_id, source_text, confidence)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (node_id, document_id, chunk_id)
DO UPDATE SET source_text = EXCLUDED.source_text, confidence = EXCLUDED.confidence
`

type UpsertNodeSourceParams struct {
	NodeID     string
	DocumentID string
	ChunkID    string
	SourceText string
	Confidence sql.NullFloat64
}

func (q *Queries) UpsertNodeSource(ctx context.Context, arg UpsertNodeSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeSource,
		arg.NodeID,
		arg.DocumentID,
		arg.ChunkID,
		arg.SourceText,
		arg.Confidence,
	)
	return err
}

const upsertRejectedAlias = `-- name: UpsertRejectedAlias :exec
INSERT INTO node_aliases (workspace_id, canonical_node_id, alias_node_id, status, updated_at)
VALUES ($1, $2, $3, 'rejected', $4)
ON CONFLICT (workspace_id, canonical_node_id, alias_node_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = EXCLUDED.updated_at
`

type UpsertRejectedAliasParams struct {
	WorkspaceID     string
	CanonicalNodeID string
	AliasNodeID     string
	UpdatedAt       time.Time
}

func (q *Queries) UpsertRejectedAlias(ctx context.Context, arg UpsertRejectedAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertRejectedAlias,
		arg.WorkspaceID,
		arg.CanonicalNodeID,
		arg.AliasNodeID,
		arg.UpdatedAt,
	)
	return err
}

const getSubtreeNodes = `-- name: GetSubtreeNodes :many
WITH RECURSIVE subtree AS (
  SELECT node_id, graph_id, label, category, level, entity_type, description, summary_html, created_by, created_at, 0 AS rel_depth
  FROM nodes WHERE node_id = $1
  UNION ALL
  SELECT n.node_id, n.graph_id, n.label, n.category, n.level, n.entity_type, n.description, n.summary_html, n.created_by, n.created_at, s.rel_depth + 1
  FROM nodes n
  JOIN edges e ON e.target_node_id = n.node_id AND e.edge_type = 'hierarchical'
  JOIN subtree s ON s.node_id = e.source_node_id
  WHERE s.rel_depth < $2
)
SELECT node_id, graph_id, label, category, level, entity_type, description, summary_html, created_by, created_at,
  EXISTS(
    SELECT 1 FROM edges e2
    WHERE e2.source_node_id = subtree.node_id AND e2.edge_type = 'hierarchical'
  ) AS has_children
FROM subtree`

type GetSubtreeNodesParams struct {
	NodeID   string
	MaxDepth int32
}

type GetSubtreeNodesRow struct {
	NodeID      string
	GraphID     string
	Label       string
	Category    string
	Level       int32
	EntityType  string
	Description string
	SummaryHtml string
	CreatedBy   string
	CreatedAt   time.Time
	HasChildren bool
}

func (q *Queries) GetSubtreeNodes(ctx context.Context, arg GetSubtreeNodesParams) ([]GetSubtreeNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubtreeNodes, arg.NodeID, arg.MaxDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubtreeNodesRow
	for rows.Next() {
		var i GetSubtreeNodesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.GraphID,
			&i.Label,
			&i.Category,
			&i.Level,
			&i.EntityType,
			&i.Description,
			&i.SummaryHtml,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.HasChildren,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubtreeEdges = `-- name: GetSubtreeEdges :many
WITH RECURSIVE subtree AS (
  SELECT node_id, 0 AS rel_depth FROM nodes WHERE node_id = $1
  UNION ALL
  SELECT n.node_id, s.rel_depth + 1
  FROM nodes n
  JOIN edges e ON e.target_node_id = n.node_id AND e.edge_type = 'hierarchical'
  JOIN subtree s ON s.node_id = e.source_node_id
  WHERE s.rel_depth < $2
)
SELECT e.edge_id, e.graph_id, e.source_node_id, e.target_node_id, e.edge_type, e.description, e.created_at
FROM edges e
JOIN subtree src ON src.node_id = e.source_node_id
JOIN subtree tgt ON tgt.node_id = e.target_node_id
WHERE e.edge_type = 'hierarchical'`

type GetSubtreeEdgesParams struct {
	NodeID   string
	MaxDepth int32
}

func (q *Queries) GetSubtreeEdges(ctx context.Context, arg GetSubtreeEdgesParams) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, getSubtreeEdges, arg.NodeID, arg.MaxDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.EdgeID,
			&i.GraphID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.EdgeType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
