// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type Account struct {
	AccountID          string
	Name               string
	Plan               string
	StorageQuotaBytes  int64
	StorageUsedBytes   int64
	MaxFileSizeBytes   int64
	MaxUploadsPer5h    int64
	MaxUploadsPer1week int64
	CreatedAt          time.Time
}

type AccountUser struct {
	AccountID string
	UserID    string
	Role      string
	JoinedAt  time.Time
}

type Document struct {
	DocumentID  string
	WorkspaceID string
	UploadedBy  string
	Filename    string
	MimeType    string
	FileSize    int64
	CreatedAt   time.Time
}

type DocumentProcessingJob struct {
	JobID        string
	DocumentID   string
	GraphID      sql.NullString
	JobType      string
	Status       string
	CurrentStage string
	ErrorMessage string
	ParamsJson   string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Edge struct {
	EdgeID       string
	GraphID      string
	SourceNodeID string
	TargetNodeID string
	EdgeType     string
	Description  string
	CreatedAt    time.Time
}

type EdgeSource struct {
	EdgeID     string
	DocumentID string
	ChunkID    string
	SourceText string
	Confidence sql.NullFloat64
}

type Graph struct {
	GraphID     string
	WorkspaceID string
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Node struct {
	NodeID      string
	GraphID     string
	Label       string
	Category    string
	Level       int32
	EntityType  string
	Description string
	SummaryHtml string
	CreatedBy   string
	CreatedAt   time.Time
}

type NodeAlias struct {
	WorkspaceID     string
	CanonicalNodeID string
	AliasNodeID     string
	Status          string
	UpdatedAt       time.Time
}

type NodeSource struct {
	NodeID     string
	DocumentID string
	ChunkID    string
	SourceText string
	Confidence sql.NullFloat64
}

type Workspace struct {
	WorkspaceID string
	AccountID   string
	Name        string
	CreatedAt   time.Time
}
