// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	pgvector "github.com/pgvector/pgvector-go"
)

type Account struct {
	AccountID          string
	Name               string
	Plan               string
	StorageQuotaBytes  int64
	StorageUsedBytes   int64
	MaxFileSizeBytes   int64
	MaxUploadsPer5h    int32
	MaxUploadsPer1week int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type AccountUser struct {
	AccountID string
	UserID    string
	Role      string
	JoinedAt  time.Time
}

type Document struct {
	DocumentID  string
	WorkspaceID string
	UploadedBy  string
	Filename    string
	MimeType    string
	FileSize    int64
	CreatedAt   time.Time
}

type DocumentChunk struct {
	ChunkID    string
	DocumentID string
	Heading    string
	Text       string
	SourcePage sql.NullInt32
	Embedding  pgvector.Vector
}

type DocumentProcessingJob struct {
	JobID            string
	DocumentID       string
	WorkspaceID      string
	JobType          string
	Status           string
	CurrentStage     string
	ErrorMessage     string
	ParamsJson       string
	RequestedBy      string
	CapabilityID     string
	ExecutionPlanID  string
	PlanStatus       string
	EvaluationStatus string
	RetryCount       int32
	BudgetJson       string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ItemAlias struct {
	WorkspaceID     string
	CanonicalItemID string
	AliasItemID     string
	Status          string
	UpdatedAt       time.Time
}

type ItemSource struct {
	ItemID     string
	DocumentID string
	ChunkID    string
	SourceText string
	Confidence sql.NullFloat64
}

type JobApprovalRequest struct {
	ApprovalID              string
	JobID                   string
	PlanID                  string
	Status                  string
	RequestedOperationsJson string
	Reason                  string
	RiskTier                string
	RequestedBy             string
	ReviewedBy              string
	RequestedAt             time.Time
	ReviewedAt              sql.NullTime
}

type JobCapability struct {
	CapabilityID           string
	JobID                  string
	WorkspaceID            string
	AllowedDocumentIdsJson string
	AllowedItemIdsJson     string
	AllowedOperationsJson  string
	MaxLlmCalls            int32
	MaxToolRuns            int32
	MaxItemCreations       int32
	ExpiresAt              time.Time
	CreatedAt              time.Time
}

type JobExecutionPlan struct {
	PlanID    string
	JobID     string
	Status    string
	Summary   string
	PlanJson  string
	CreatedBy string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type JobLog struct {
	ID          string
	JobID       string
	WorkspaceID string
	DocumentID  string
	Level       string
	Event       string
	Message     string
	DetailJson  json.RawMessage
	CreatedAt   time.Time
}

type JobMutationLog struct {
	MutationID     string
	JobID          string
	PlanID         string
	CapabilityID   string
	WorkspaceID    string
	TargetType     string
	TargetID       string
	MutationType   string
	RiskTier       string
	BeforeJson     string
	AfterJson      string
	ProvenanceJson string
	CreatedAt      time.Time
}

type TreeItem struct {
	ID                string
	WorkspaceID       string
	ParentID          sql.NullString
	Title             string
	Level             int32
	Description       string
	Content           string
	OverrideCss       string
	CreatedBy         string
	GovernanceState   string
	LastMutationJobID string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Workspace struct {
	WorkspaceID string
	AccountID   string
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
