// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tree.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const countJobMutationsByTarget = `-- name: CountJobMutationsByTarget :one
SELECT COUNT(*)
FROM job_mutation_logs
WHERE job_id = $1 AND target_type = $2
`

type CountJobMutationsByTargetParams struct {
	JobID      string
	TargetType string
}

func (q *Queries) CountJobMutationsByTarget(ctx context.Context, arg CountJobMutationsByTargetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobMutationsByTarget, arg.JobID, arg.TargetType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :exec
INSERT INTO tree_items (id, workspace_id, parent_id, title, level, description, content, override_css, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
`

type CreateItemParams struct {
	ID          string
	WorkspaceID string
	ParentID    sql.NullString
	Title       string
	Level       int32
	Description string
	Content     string
	OverrideCss string
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Title,
		arg.Level,
		arg.Description,
		arg.Content,
		arg.OverrideCss,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createStructuredItem = `-- name: CreateStructuredItem :exec
INSERT INTO tree_items (
  id, workspace_id, parent_id, title, level, description, content, override_css,
  created_by, governance_state, last_mutation_job_id, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12)
`

type CreateStructuredItemParams struct {
	ID                string
	WorkspaceID       string
	ParentID          sql.NullString
	Title             string
	Level             int32
	Description       string
	Content           string
	OverrideCss       string
	CreatedBy         string
	GovernanceState   string
	LastMutationJobID string
	CreatedAt         time.Time
}

func (q *Queries) CreateStructuredItem(ctx context.Context, arg CreateStructuredItemParams) error {
	_, err := q.db.ExecContext(ctx, createStructuredItem,
		arg.ID,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Title,
		arg.Level,
		arg.Description,
		arg.Content,
		arg.OverrideCss,
		arg.CreatedBy,
		arg.GovernanceState,
		arg.LastMutationJobID,
		arg.CreatedAt,
	)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, workspace_id, parent_id, title, level, description, content, override_css, created_by,
       COALESCE(governance_state, 'system_generated') AS governance_state, created_at
FROM tree_items
WHERE id = $1
`

type GetItemRow struct {
	ID              string
	WorkspaceID     string
	ParentID        sql.NullString
	Title           string
	Level           int32
	Description     string
	Content         string
	OverrideCss     string
	CreatedBy       string
	GovernanceState string
	CreatedAt       time.Time
}

func (q *Queries) GetItem(ctx context.Context, id string) (GetItemRow, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i GetItemRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Title,
		&i.Level,
		&i.Description,
		&i.Content,
		&i.OverrideCss,
		&i.CreatedBy,
		&i.GovernanceState,
		&i.CreatedAt,
	)
	return i, err
}

const getItemSummaryUpdateContext = `-- name: GetItemSummaryUpdateContext :one
SELECT workspace_id, COALESCE(content, '') AS content, COALESCE(governance_state, 'system_generated') AS governance_state
FROM tree_items
WHERE id = $1
`

type GetItemSummaryUpdateContextRow struct {
	WorkspaceID     string
	Content         string
	GovernanceState string
}

func (q *Queries) GetItemSummaryUpdateContext(ctx context.Context, id string) (GetItemSummaryUpdateContextRow, error) {
	row := q.db.QueryRowContext(ctx, getItemSummaryUpdateContext, id)
	var i GetItemSummaryUpdateContextRow
	err := row.Scan(&i.WorkspaceID, &i.Content, &i.GovernanceState)
	return i, err
}

const getTreeRoot = `-- name: GetTreeRoot :one
SELECT id, workspace_id, parent_id, title, level, description, content, override_css, created_by, created_at
FROM tree_items
WHERE workspace_id = $1 AND parent_id IS NULL
LIMIT 1
`

type GetTreeRootRow struct {
	ID          string
	WorkspaceID string
	ParentID    sql.NullString
	Title       string
	Level       int32
	Description string
	Content     string
	OverrideCss string
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) GetTreeRoot(ctx context.Context, workspaceID string) (GetTreeRootRow, error) {
	row := q.db.QueryRowContext(ctx, getTreeRoot, workspaceID)
	var i GetTreeRootRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Title,
		&i.Level,
		&i.Description,
		&i.Content,
		&i.OverrideCss,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertJobMutationLog = `-- name: InsertJobMutationLog :exec
INSERT INTO job_mutation_logs (
  mutation_id, job_id, plan_id, capability_id, workspace_id, target_type, target_id, mutation_type,
  risk_tier, before_json, after_json, provenance_json, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertJobMutationLogParams struct {
	MutationID     string
	JobID          string
	PlanID         string
	CapabilityID   string
	WorkspaceID    string
	TargetType     string
	TargetID       string
	MutationType   string
	RiskTier       string
	BeforeJson     string
	AfterJson      string
	ProvenanceJson string
	CreatedAt      time.Time
}

func (q *Queries) InsertJobMutationLog(ctx context.Context, arg InsertJobMutationLogParams) error {
	_, err := q.db.ExecContext(ctx, insertJobMutationLog,
		arg.MutationID,
		arg.JobID,
		arg.PlanID,
		arg.CapabilityID,
		arg.WorkspaceID,
		arg.TargetType,
		arg.TargetID,
		arg.MutationType,
		arg.RiskTier,
		arg.BeforeJson,
		arg.AfterJson,
		arg.ProvenanceJson,
		arg.CreatedAt,
	)
	return err
}

const listChildItems = `-- name: ListChildItems :many
SELECT id, workspace_id, parent_id, title, level, description, content, override_css, created_by,
  COALESCE(governance_state, 'system_generated') AS governance_state, created_at,
  EXISTS(SELECT 1 FROM tree_items child WHERE child.parent_id = tree_items.id) AS has_children
FROM tree_items
WHERE tree_items.parent_id = $1
`

type ListChildItemsRow struct {
	ID              string
	WorkspaceID     string
	ParentID        sql.NullString
	Title           string
	Level           int32
	Description     string
	Content         string
	OverrideCss     string
	CreatedBy       string
	GovernanceState string
	CreatedAt       time.Time
	HasChildren     bool
}

func (q *Queries) ListChildItems(ctx context.Context, parentID sql.NullString) ([]ListChildItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChildItems, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildItemsRow
	for rows.Next() {
		var i ListChildItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Title,
			&i.Level,
			&i.Description,
			&i.Content,
			&i.OverrideCss,
			&i.CreatedBy,
			&i.GovernanceState,
			&i.CreatedAt,
			&i.HasChildren,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSources = `-- name: ListItemSources :many
SELECT item_id, document_id, chunk_id, source_text, COALESCE(confidence, 0) AS confidence
FROM item_sources
WHERE item_id = $1
`

type ListItemSourcesRow struct {
	ItemID     string
	DocumentID string
	ChunkID    string
	SourceText string
	Confidence float64
}

func (q *Queries) ListItemSources(ctx context.Context, itemID string) ([]ListItemSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemSources, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemSourcesRow
	for rows.Next() {
		var i ListItemSourcesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.DocumentID,
			&i.ChunkID,
			&i.SourceText,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByWorkspace = `-- name: ListItemsByWorkspace :many
SELECT id, workspace_id, parent_id, title, level, description, content, override_css, created_by,
       COALESCE(governance_state, 'system_generated') AS governance_state, created_at
FROM tree_items
WHERE workspace_id = $1
ORDER BY created_at ASC
`

type ListItemsByWorkspaceRow struct {
	ID              string
	WorkspaceID     string
	ParentID        sql.NullString
	Title           string
	Level           int32
	Description     string
	Content         string
	OverrideCss     string
	CreatedBy       string
	GovernanceState string
	CreatedAt       time.Time
}

func (q *Queries) ListItemsByWorkspace(ctx context.Context, workspaceID string) ([]ListItemsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByWorkspaceRow
	for rows.Next() {
		var i ListItemsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Title,
			&i.Level,
			&i.Description,
			&i.Content,
			&i.OverrideCss,
			&i.CreatedBy,
			&i.GovernanceState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemParent = `-- name: UpdateItemParent :exec
UPDATE tree_items
SET parent_id = $2, updated_at = $3
WHERE id = $1
`

type UpdateItemParentParams struct {
	ID        string
	ParentID  sql.NullString
	UpdatedAt time.Time
}

func (q *Queries) UpdateItemParent(ctx context.Context, arg UpdateItemParentParams) error {
	_, err := q.db.ExecContext(ctx, updateItemParent, arg.ID, arg.ParentID, arg.UpdatedAt)
	return err
}

const updateItemSummaryAndMutation = `-- name: UpdateItemSummaryAndMutation :execrows
UPDATE tree_items
SET content = $2, last_mutation_job_id = $3, updated_at = $4
WHERE id = $1
`

type UpdateItemSummaryAndMutationParams struct {
	ID                string
	Content           string
	LastMutationJobID string
	UpdatedAt         time.Time
}

func (q *Queries) UpdateItemSummaryAndMutation(ctx context.Context, arg UpdateItemSummaryAndMutationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateItemSummaryAndMutation,
		arg.ID,
		arg.Content,
		arg.LastMutationJobID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTreeTimestamp = `-- name: UpdateTreeTimestamp :exec
UPDATE tree_items
SET updated_at = $2
WHERE workspace_id = (SELECT workspace_id FROM tree_items WHERE tree_items.id = $1 LIMIT 1)
`

type UpdateTreeTimestampParams struct {
	ID        string
	UpdatedAt time.Time
}

func (q *Queries) UpdateTreeTimestamp(ctx context.Context, arg UpdateTreeTimestampParams) error {
	_, err := q.db.ExecContext(ctx, updateTreeTimestamp, arg.ID, arg.UpdatedAt)
	return err
}

const upsertApprovedAlias = `-- name: UpsertApprovedAlias :exec
INSERT INTO item_aliases (workspace_id, canonical_item_id, alias_item_id, status, updated_at)
VALUES ($1, $2, $3, 'approved', $4)
ON CONFLICT (workspace_id, canonical_item_id, alias_item_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = EXCLUDED.updated_at
`

type UpsertApprovedAliasParams struct {
	WorkspaceID     string
	CanonicalItemID string
	AliasItemID     string
	UpdatedAt       time.Time
}

func (q *Queries) UpsertApprovedAlias(ctx context.Context, arg UpsertApprovedAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertApprovedAlias,
		arg.WorkspaceID,
		arg.CanonicalItemID,
		arg.AliasItemID,
		arg.UpdatedAt,
	)
	return err
}

const upsertItemSource = `-- name: UpsertItemSource :exec
INSERT INTO item_sources (item_id, document_id, chunk_id, source_text, confidence)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (item_id, document_id, chunk_id)
DO UPDATE SET source_text = EXCLUDED.source_text, confidence = EXCLUDED.confidence
`

type UpsertItemSourceParams struct {
	ItemID     string
	DocumentID string
	ChunkID    string
	SourceText string
	Confidence sql.NullFloat64
}

func (q *Queries) UpsertItemSource(ctx context.Context, arg UpsertItemSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertItemSource,
		arg.ItemID,
		arg.DocumentID,
		arg.ChunkID,
		arg.SourceText,
		arg.Confidence,
	)
	return err
}

const upsertRejectedAlias = `-- name: UpsertRejectedAlias :exec
INSERT INTO item_aliases (workspace_id, canonical_item_id, alias_item_id, status, updated_at)
VALUES ($1, $2, $3, 'rejected', $4)
ON CONFLICT (workspace_id, canonical_item_id, alias_item_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = EXCLUDED.updated_at
`

type UpsertRejectedAliasParams struct {
	WorkspaceID     string
	CanonicalItemID string
	AliasItemID     string
	UpdatedAt       time.Time
}

func (q *Queries) UpsertRejectedAlias(ctx context.Context, arg UpsertRejectedAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertRejectedAlias,
		arg.WorkspaceID,
		arg.CanonicalItemID,
		arg.AliasItemID,
		arg.UpdatedAt,
	)
	return err
}
