// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAccountUser = `-- name: CreateAccountUser :exec
INSERT INTO account_users (account_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, user_id) DO NOTHING
`

type CreateAccountUserParams struct {
	AccountID string
	UserID    string
	Role      string
	JoinedAt  time.Time
}

func (q *Queries) CreateAccountUser(ctx context.Context, arg CreateAccountUserParams) error {
	_, err := q.db.ExecContext(ctx, createAccountUser,
		arg.AccountID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (workspace_id, account_id, name, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateWorkspaceParams struct {
	WorkspaceID string
	AccountID   string
	Name        string
	CreatedAt   time.Time
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.WorkspaceID,
		arg.AccountID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT account_id, name, plan, storage_quota_bytes, storage_used_bytes, max_file_size_bytes, max_uploads_per_5h, max_uploads_per_1week, created_at
FROM accounts
WHERE account_id = $1
`

func (q *Queries) GetAccount(ctx context.Context, accountID string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, accountID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Name,
		&i.Plan,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.MaxFileSizeBytes,
		&i.MaxUploadsPer5h,
		&i.MaxUploadsPer1week,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByUser = `-- name: GetAccountByUser :one
SELECT a.account_id, a.name, a.plan, a.storage_quota_bytes, a.storage_used_bytes, a.max_file_size_bytes, a.max_uploads_per_5h, a.max_uploads_per_1week, a.created_at
FROM accounts a
JOIN account_users au ON au.account_id = a.account_id
WHERE au.user_id = $1
LIMIT 1
`

func (q *Queries) GetAccountByUser(ctx context.Context, userID string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUser, userID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Name,
		&i.Plan,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.MaxFileSizeBytes,
		&i.MaxUploadsPer5h,
		&i.MaxUploadsPer1week,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateAccount = `-- name: GetOrCreateAccount :one
INSERT INTO accounts (account_id, name, plan, storage_quota_bytes, storage_used_bytes, max_file_size_bytes, max_uploads_per_5h, max_uploads_per_1week, created_at)
VALUES ($1, $2, $3, $4, 0, $5, $6, $7, $8)
ON CONFLICT (account_id) DO UPDATE SET account_id = EXCLUDED.account_id
RETURNING account_id, name, plan, storage_quota_bytes, storage_used_bytes, max_file_size_bytes, max_uploads_per_5h, max_uploads_per_1week, created_at
`

type GetOrCreateAccountParams struct {
	AccountID          string
	Name               string
	Plan               string
	StorageQuotaBytes  int64
	MaxFileSizeBytes   int64
	MaxUploadsPer5h    int64
	MaxUploadsPer1week int64
	CreatedAt          time.Time
}

func (q *Queries) GetOrCreateAccount(ctx context.Context, arg GetOrCreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateAccount,
		arg.AccountID,
		arg.Name,
		arg.Plan,
		arg.StorageQuotaBytes,
		arg.MaxFileSizeBytes,
		arg.MaxUploadsPer5h,
		arg.MaxUploadsPer1week,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Name,
		&i.Plan,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.MaxFileSizeBytes,
		&i.MaxUploadsPer5h,
		&i.MaxUploadsPer1week,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT workspace_id, account_id, name, created_at
FROM workspaces
WHERE workspace_id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, workspaceID string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, workspaceID)
	var i Workspace
	err := row.Scan(
		&i.WorkspaceID,
		&i.AccountID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const isWorkspaceAccessible = `-- name: IsWorkspaceAccessible :one
SELECT EXISTS(
  SELECT 1 FROM workspaces w
  JOIN account_users au ON au.account_id = w.account_id
  WHERE w.workspace_id = $1 AND au.user_id = $2
)::bool AS accessible
`

type IsWorkspaceAccessibleParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) IsWorkspaceAccessible(ctx context.Context, arg IsWorkspaceAccessibleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isWorkspaceAccessible, arg.WorkspaceID, arg.UserID)
	var accessible bool
	err := row.Scan(&accessible)
	return accessible, err
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT w.workspace_id, w.account_id, w.name, w.created_at
FROM workspaces w
JOIN account_users au ON au.account_id = w.account_id
WHERE au.user_id = $1
ORDER BY w.created_at DESC
`

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID string) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.AccountID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
